dist: trusty
sudo: required
cache:
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
matrix:
  include:
  - env: BUILD=stack ARGS=""
    compiler: ": #stack 8.0.1"
    addons:
      apt:
        packages:
        - ghc-8.0.1
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="" osx
    compiler: ": #stack 8.0.1"
    os: osx
  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24
    compiler: ": #GHC 8.0.1"
    addons:
      apt:
        packages:
        - cabal-install-1.24
        - ghc-8.0.1
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6
        sources:
        - hvr-ghc
  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24 osx
    compiler: ": #GHC 8.0.1"
    addons:
      apt:
        packages:
        - cabal-install-1.24
        - ghc-8.0.1
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6
        sources:
        - hvr-ghc
    os: osx
  - env: BUILD=cabal GHCVER=head  CABALVER=head
    compiler: ": #GHC HEAD"
    addons:
      apt:
        packages:
        - cabal-install-head
        - ghc-head
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons:
      apt:
        packages:
        - libgmp-dev
  allow_failures:
  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24
  - env: BUILD=stack ARGS="--resolver nightly"
  - env: BUILD=cabal GHCVER=head  CABALVER=head
  - env: BUILD=stack ARGS="" osx
  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24 osx
  fast_finish: true
before_install:
- unset CC
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
- sudo dd if=/dev/zero of=/swapfile bs=1M count=1024
- sudo mkswap /swapfile
- sudo swapon /swapfile
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- chmod +x ./travis_long
- if [ -f configure.ac ]; then autoreconf -i; fi
- PATH=$PATH:~/.cabal/bin
- "case \"$BUILD\" in\n  stack)\n    stack --no-terminal --install-ghc $ARGS test
  --only-dependencies\n    ;;\n  cabal)\n    cabal --version\n    travis_retry cabal
  update\n    cabal install --enable-tests \n    ;;\nesac\n"
- mkdir dist/bin
before_script: composer install
script:
- |
  case "$BUILD" in
    stack)
    ./travis_long stack --no-terminal --local-bin-path=dist/bin --copy-bins $ARGS build
      ;;
    cabal)
    ./travis_long cabal test
      ;;
  esac
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: zJj7c/nbpUdHdJXEuJIbu75zrSv8E8jbMthH3i4e8t8hFqT1NL0+aJBsHjxg07pt6PugtB42C5ND83DRlc1w0tmwp2wE43u/PcrureKUw6wcfErOrmTq71wttwR6Xgw+wd7JDRa0UxZVEk2MuDeHMZHVpbYjkqwZxtIwlQzFw59m/FAIu1J6CgVMnoXlT2xQEA0cDbaHwYQdv3dQwDstchbo/ZgoTY8p+g7EnSe62VrtoUHx1+zithu7Rn5WVpp7CtyELh0tFqfnAzR9vcZpdi0e1b5nt1fCAtNKi2ZgKFLFlxY0mKG8Zqr8Gp0xVnUPW7SL4UUEwPZaJj32CXJZYNkaMSNrK6pkG1Qi6G7R8JZ049KZMyxFOKiuexs78+cFqAQE/cECGiOVE1l2yjzQJOyB2/pd1wkTaCMYq6mSfwlJJj4UXjPR9DpHxQ78MfKePr6hKzWU5GM6ZtyLfZhAdDkqOtlQMHcfXZ1efvmmcu0QOaF+p4YxpGIkbhYow8669mBQnOZTUzISOBJObYYY3SAhuvVhJ4FXmrsPRC+kIX062kS3inQI6MfuxCSVnbcM4/Hgb9YC+VeyA0yh6CGz8adq88MDV+5Ki7z8SvB2s3NJvL0ReEqD5A3ZSpoDBmpCbtkh240YPHaUNQdeCwXo+u6G82K7peUGeZ3k2oNxog8=
  file: dist/bin/ampersand
  on:
    repo: hidde-jan/Ampersand
    tags: true
    condition: $BUILD = stack
