flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- SpreadsheetML-0.1
- hgal-2.0.0.2
- pandoc-1.17.1
- rdf4h-2.0.0
- simple-sql-parser-0.4.1
- text-1.2.2.1
- yaml-0.8.17.1
- yaml-config-0.4.0
resolver: lts-6.2
